#if !defined _ARRAYS_
#define _ARRAYS_

new pVars[MAX_PLAYERS][MAX_NUM_CHARS][PlayerData];
new chName[10][CharName] = {
	{"Marcin", false},
	{"Tomasz", false},
	{"Marian", false},
	{"Waldemar", false},
	{"Janusz", false},
	{"Maciej", false},
	{"Jakub", false},
	{"Piotr", false},
	{"Robert", false},
	{"Franciszek", false}
};
new chSur[10][CharSurName] = {
	{"Nowak", false},
	{"Kowalski", false},
	{"Zamoyski", false},
	{"Urban", false},
	{"Jarosz", false},
	{"Kozak", false},
	{"Wisniowski", false},
	{"Dabrowski", false},
	{"Oracz", false},
	{"Kopacz", false},
};

#endif 