/*
	Project: SAMP-RP
	Author: steeZ (macpilch)
	File: dialogs.inc
	Date: 25.07.2022
	Modified: 01.08.2022
*/

#if !defined _DIALOGS_
#define _DIALOGS_

#define DIALOG_REGISTER 1
#define DIALOG_LOGIN 2
#define DIALOG_REGISTER_SURNAME 3
#define DIALOG_REGISTER_NAME 4
#define DIALOG_REGISTER_PASS 5
#define DIALOG_LOGIN_PASS 6
#define DIALOG_LOGIN_CHANGE_CHAR 7
#define DIALOG_HELP 8
#define DIALOG_STATS 9
#define DIALOG_DEFAULT 999

#endif 